server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      transaction-id-prefix: order-service-${random.value}-
