server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_message_event
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094

